solids:
  ingest:
    config:
      input_file_path: s3://roche-twde-datapipeline-spike-data/datasets/ingestion/input/
      output_file_path: s3://roche-twde-datapipeline-spike-data/datasets/ingestion/output-emr/
  transform:
    config:
      transformation_output_path: s3://roche-twde-datapipeline-spike-data/datasets/transformation/output-emr/
