solids:
  ingest:
    config:
      input_file_path: ./userdata_pipeline/tests/data/ingestion/input/
      output_file_path: ./userdata_pipeline/tests/data/ingestion/output/
  transform:
    config:
      transformation_output_path: ./userdata_pipeline/tests/data/transformation/output/
